### PR TITLE
RDCC-2045: Adding new Unspec CCD roles

### PR DESCRIPTION
**Pull request by AdilOoze**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RDCC-2045

### Change description ###

Added new `unspec_service` CCD roles:
1. caseworker-civil
2. caseworker-civil-solicitor
3. caseworker-civil-systemupdate

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by shreedhar-hmcts — APPROVED** [review]

**Review by shreedhar-hmcts — COMMENTED** [review]
Please confirm this is tested with keeping new roles enabled and disabled on AAT

**Review by dharmendrak — APPROVED** [review]

**Review by dharmendrak — COMMENTED** [review]
Do we need to add jurisdiction `CIVIL` as well? as this is not same as `CMC` Jurisdiction

**Review by dharmendrak — COMMENTED** [review]
Please remove the entry for `caseworker-civil-systemupdate`

**Comment by shreedhar-hmcts** [comment]
closing this as already merged to master

**Pull request closed without merging**
